conda_build_tool: rattler-build
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
provider:
  osx_arm64: default
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
